const buildMember = ({
  id,
  name,
  role,
  dept,
  title,
  skills,
  image,
  position,
  intro,
  strengths,
  status,
  clearance,
  leadershipRole,
  socialLinks = [],
}) => ({
  id,
  name,
  role,
  dept,
  title,
  skills,
  image,
  position,
  intro,
  strengths,
  status,
  clearance,
  leadershipRole,
  socialLinks,
});

export const teamData = [
  {
    category: "Leadership",
    members: [
      buildMember({
        id: "ldr-01",
        name: "Devansh Katkar",
        role: "President",
        dept: "Leadership",
        title: "President, DevLeague DLCC 2026",
        skills: ["Vision Architecture", "Growth Strategy", "Execution Systems"],
        image: "/Devansh.jpeg",
        position: "center 20%",
        intro: "Leads the DevLeague ecosystem with a founder-level mindset, aligning teams, events, and execution standards around one elite operating vision.",
        strengths: ["Decisive leadership", "Cross-team orchestration", "High-agency execution"],
        status: "ELITE COMMAND",
        clearance: "MAX",
        leadershipRole: "Primary command authority for the DLCC 2026 core team reveal and strategic direction.",
      }),
      buildMember({
        id: "ldr-02",
        name: "Jeet Dubey",
        role: "Vice President",
        dept: "Leadership",
        title: "Vice President, Core Operations",
        skills: ["Operations", "Team Management", "Strategic Planning"],
        image: "/Jeet Dubey.jpeg",
        position: "center",
        intro: "Translates leadership vision into execution rhythm, ensuring every division operates with structure, accountability, and precision.",
        strengths: ["Operational discipline", "Team coordination", "Decision support"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Second-line command for internal alignment, planning cadence, and delivery control.",
      }),
    ],
  },
  {
    category: "Technical Team",
    members: [
      buildMember({
        id: "tec-01",
        name: "Shehzan Khan",
        role: "Technical Lead",
        dept: "Technical",
        title: "Technical Lead, Systems & Product Engineering",
        skills: ["System Design", "Full-Stack Development", "Technical Mentoring"],
        image: "/Shehzan Khan.jpg",
        position: "center 15%",
        intro: "Guides technical execution across builds, architecture decisions, and implementation quality for the DevLeague network.",
        strengths: ["Architecture clarity", "Technical ownership", "Builder mindset"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Heads the technical division and sets implementation standards for major releases.",
      }),
      buildMember({
        id: "tec-02",
        name: "Diya Rawat",
        role: "Core Member",
        dept: "Technical",
        title: "Frontend Systems Contributor",
        skills: ["Frontend Engineering", "UI Design", "Implementation"],
        image: "/Diya Rawat.jpeg",
        position: "center 10%",
        intro: "Builds polished user experiences that merge functionality, usability, and visual consistency for high-impact product surfaces.",
        strengths: ["Interface precision", "Design translation", "Execution speed"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports high-visibility technical deliverables and user-facing systems.",
      }),
      buildMember({
        id: "tec-03",
        name: "Praveen Sharma",
        role: "Core Member",
        dept: "Technical",
        title: "Backend Logic & Systems Contributor",
        skills: ["Backend Development", "Logic Engineering", "Problem Solving"],
        image: "/Praveen.jpeg",
        position: "center 20%",
        intro: "Focuses on stable logic, dependable implementation, and solving technical problems with a clear systems-first mindset.",
        strengths: ["Logical depth", "Backend support", "Reliable execution"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Supports core engineering execution and technical backbone tasks.",
      }),
      buildMember({
        id: "tec-04",
        name: "Khushi Jain",
        role: "Core Member",
        dept: "Technical",
        title: "Documentation & Interface Support",
        skills: ["Documentation", "UI Support", "Product Assistance"],
        image: "/Khushi Jain.jpeg",
        position: "center",
        intro: "Strengthens the technical team through clean support workflows, polished documentation, and user-facing coordination.",
        strengths: ["Documentation hygiene", "Support execution", "Detail retention"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports clarity, continuity, and coordination across engineering deliverables.",
      }),
    ],
  },
  {
    category: "Events Team",
    members: [
      buildMember({
        id: "evt-01",
        name: "Kartikey Pandey",
        role: "Event Lead",
        dept: "Events",
        title: "Event Lead, Experience Operations",
        skills: ["Coordination", "Logistics", "Execution Management"],
        image: "/Kartikey Pandey.jpeg",
        position: "center",
        intro: "Owns execution discipline across key events, coordinating people, timelines, and on-ground precision.",
        strengths: ["Operational timing", "Logistical clarity", "Team synchronization"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Leads event delivery systems and signature execution moments.",
      }),
      buildMember({
        id: "evt-02",
        name: "Om Upadhyay",
        role: "Core Member",
        dept: "Events",
        title: "Event Planning Contributor",
        skills: ["Execution", "Planning", "Communication"],
        image: "/Om Upadhyay.jpeg",
        position: "center",
        intro: "Supports event operations with structured planning, clear communication, and dependable execution under pressure.",
        strengths: ["Execution readiness", "Coordination support", "Communication flow"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports event system readiness and smooth coordination.",
      }),
      buildMember({
        id: "evt-03",
        name: "Mehak Kuchya",
        role: "Core Member",
        dept: "Events",
        title: "Outreach & Event Support Contributor",
        skills: ["Outreach", "Coordination", "Support Systems"],
        image: "/Mehak Kuchya.jpeg",
        position: "center",
        intro: "Helps sustain event momentum through outreach support, operational follow-through, and collaborative execution.",
        strengths: ["Team support", "Operational follow-up", "Audience coordination"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Supports seamless execution of event-facing initiatives.",
      }),
    ],
  },
  {
    category: "Design Team",
    members: [
      buildMember({
        id: "des-01",
        name: "Bhumi Raghuvanshi",
        role: "Design Lead",
        dept: "Design",
        title: "Design Lead, Visual Identity Systems",
        skills: ["Creative Direction", "UI/UX", "Branding"],
        image: "/Bhumi Raghuvanshi.jpeg",
        position: "center",
        intro: "Shapes the visual identity of DevLeague with strong direction, design consistency, and premium presentation instincts.",
        strengths: ["Creative leadership", "Visual systems", "Brand consistency"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Leads visual execution, brand tone, and presentation quality across public releases.",
      }),
      buildMember({
        id: "des-02",
        name: "Vaishnavi Singh",
        role: "Core Member",
        dept: "Design",
        title: "Graphics & Layout Contributor",
        skills: ["Graphics", "Typography", "Layout"],
        image: "/Vaishnavi Singh.jpeg",
        position: "center",
        intro: "Supports the design division through strong layout instincts, visual polish, and typographic precision.",
        strengths: ["Layout balance", "Visual polish", "Creative support"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports creative execution across branded materials and reveal assets.",
      }),
    ],
  },
  {
    category: "Social Media & Marketing Team",
    members: [
      buildMember({
        id: "mkt-01",
        name: "Shagun Sharma",
        role: "Social Media & Marketing Lead",
        dept: "Marketing",
        title: "Marketing Lead, Growth & Reach",
        skills: ["Campaign Strategy", "Audience Growth", "Engagement Design"],
        image: "/Shagun Sharma.jpg",
        position: "center",
        intro: "Directs brand visibility and audience momentum through strategic campaigns and high-signal communication.",
        strengths: ["Growth strategy", "Audience understanding", "Campaign execution"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Leads digital reach, narrative framing, and public-facing momentum.",
      }),
      buildMember({
        id: "med-01",
        name: "Harsh Vijayvargiya",
        role: "Core Member - Videography",
        dept: "Media",
        title: "Videography & Motion Storytelling Contributor",
        skills: ["Filming", "Editing", "Direction"],
        image: "/Harsh Vijayvargiya.jpeg",
        position: "center",
        intro: "Captures the energy of the ecosystem through motion-first storytelling, direction, and visual pacing.",
        strengths: ["Visual narrative", "Shot discipline", "Editing rhythm"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports media production and cinematic brand storytelling.",
      }),
      buildMember({
        id: "med-02",
        name: "Shivam Raikwar",
        role: "Core Member - Photography",
        dept: "Media",
        title: "Photography & Capture Contributor",
        skills: ["Photography", "Lighting", "Creative Capture"],
        image: "/Shivam Raikwar.jpeg",
        position: "center",
        intro: "Brings visual sharpness to DevLeague through event capture, lighting awareness, and professional framing.",
        strengths: ["Photo composition", "Lighting control", "Moment capture"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Supports visual coverage and premium brand imagery.",
      }),
      buildMember({
        id: "cnt-01",
        name: "Varun Raghuvanshi",
        role: "Core Member - Content & Copywriting",
        dept: "Content",
        title: "Content Strategy & Copy Contributor",
        skills: ["Writing", "Editing", "Content Strategy"],
        image: "/Varun Raghuvanshi.jpeg",
        position: "center",
        intro: "Shapes the voice of DevLeague with strong messaging, clean copy, and strategic content framing.",
        strengths: ["Narrative clarity", "Copy precision", "Message discipline"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports outbound communication and tone-setting across channels.",
      }),
    ],
  },
  {
    category: "PR & Outreach",
    members: [
      buildMember({
        id: "pro-01",
        name: "Amrita Tetwal",
        role: "PR & Outreach Lead",
        dept: "PR",
        title: "PR Lead, Outreach & External Relations",
        skills: ["Public Relations", "Networking", "External Outreach"],
        image: "/Amrita Tetwal.jpeg",
        position: "center",
        intro: "Builds external trust and opportunity pipelines through outreach strategy, communication, and relationship-building.",
        strengths: ["External communication", "Relationship building", "Strategic outreach"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Leads external relationship channels and outreach initiatives.",
      }),
      buildMember({
        id: "pro-02",
        name: "Disha Agrawal",
        role: "Core Member",
        dept: "PR",
        title: "PR Strategy Support Contributor",
        skills: ["Communication", "Support Strategy", "Execution"],
        image: "/Disha Agrawal.jpeg",
        position: "center",
        intro: "Supports public relations operations with communication discipline, coordination, and responsive execution.",
        strengths: ["Communication support", "Coordination discipline", "Execution reliability"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports outreach execution and external communication flow.",
      }),
    ],
  },
  {
    category: "Sponsorship Team",
    members: [
      buildMember({
        id: "spn-01",
        name: "Ajay Dangi",
        role: "Sponsorship Lead",
        dept: "Sponsorship",
        title: "Sponsorship Lead, Strategic Partnerships",
        skills: ["Pitching", "Negotiation", "Partnership Development"],
        image: "/Ajay Dangi.jpeg",
        position: "center",
        intro: "Drives sponsorship conversations with a focus on positioning, value articulation, and partnership growth.",
        strengths: ["Pitch confidence", "Negotiation mindset", "Partnership thinking"],
        status: "ACTIVE",
        clearance: "HIGH",
        leadershipRole: "Leads sponsor-facing strategy and partnership outreach.",
      }),
      buildMember({
        id: "spn-02",
        name: "Sanket Patenkar",
        role: "Core Member",
        dept: "Sponsorship",
        title: "Sponsorship Support Contributor",
        skills: ["Execution Support", "Documentation", "Follow-through"],
        image: "/Sanket Patenkar.jpeg",
        position: "center",
        intro: "Supports sponsorship processes with dependable execution, documentation structure, and operational continuity.",
        strengths: ["Support discipline", "Execution follow-up", "Process continuity"],
        status: "VERIFIED",
        clearance: "HIGH",
        leadershipRole: "Supports partnership operations and sponsor workflow delivery.",
      }),
    ],
  },
];
